eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.161:8761/eureka/
      #, http://192.168.0.161:8762/eureka/, http://192.168.0.161:8763/eureka/
  instance:
    hostname: eurekaClientName
spring:
  application:
    name: eurekaclient