eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.182:8763/eureka/
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
spring:
  application:
    name: eureka
server:
  port: 8763